server:
  port: 7212
spring:
  application:
    name: Order-server
  redis:
    host: 101.34.103.51
    port: 6379
    password: hwq666
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  datasource:
    url: jdbc:mysql://101.34.103.51:3306/ls_db_order?Unicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource #更换为指定连接池
  rabbitmq:
    host: 101.34.103.51
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初识的失败等待时长为1秒
          multiplier: 3 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数,默认3次
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false

  cloud:
    nacos:
      discovery:
        server-addr: 101.34.103.51:8848